### ISSUE TITLE
All List and some Sorted Set commands mot implemented

### ISSUE THREAD

**Issue by IgLiv** [ssdb/dotnetssdb#2]
Hi,
I'd like to know if you are planning on implementing all of the list commands available?
Also complete the Sorted Set commands such as qpush_front, qpush_back.

Thanks

**Comment by ideawu** [comment]
I never aim to implement ALL commands, but I will implement as many commands as possible. You can ask for any command you require.

**Comment by ideawu** [comment]
No, I am expecting some other people(if any) to do this work. Because this api for .Net is not popular, I decided not to pay time on it.

**Comment by IgLiv** [comment]
Ok, hope to finish testing the added function and do a pull request
